# Generated by Django 6.1.1 on 2026-10-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_products', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ORIGINAL', 'Original'), ('OIL', 'Oil'), ('COMMERCIAL', 'Commercial'), ('STANDARD', 'Standard')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_configurations', to='catalog.merchantproduct')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configurations', to='catalog.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='SellingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('aging', models.CharField(blank=True, choices=[('AGED', 'Aged'), ('NON_AGED', 'Non-aged')], max_length=10, null=True)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_mode', models.CharField(blank=True, choices=[('FULL_BOTTLE', 'Full Bottle'), ('PORTION', 'Portion')], max_length=20, null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_cases', to='catalog.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSellingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_case_configurations', to='catalog.merchantproducttype')),
                ('selling_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configurations', to='catalog.sellingcase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='merchantproduct',
            constraint=models.UniqueConstraint(fields=('merchant', 'product'), name='unique_merchant_product'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_type'),
        ),
        migrations.AddConstraint(
            model_name='merchantproducttype',
            constraint=models.UniqueConstraint(fields=('merchant_product', 'product_type'), name='unique_merchant_product_type'),
        ),
        migrations.AddConstraint(
            model_name='sellingcase',
            constraint=models.UniqueConstraint(fields=('product_type', 'quality', 'aging', 'grade', 'sale_mode'), name='unique_selling_case', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='sellingcase',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), ('grade__gt', 0), _connector='OR'), name='selling_case_grade_positive'),
        ),
        migrations.AddConstraint(
            model_name='merchantsellingcase',
            constraint=models.UniqueConstraint(fields=('merchant_product_type', 'selling_case'), name='unique_merchant_selling_case'),
        ),
    ]
