# Generated by Django 6.1.1 on 2026-09-25 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_cases', to='catalog.producttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_type_name'),
        ),
        migrations.AddConstraint(
            model_name='sellingcase',
            constraint=models.UniqueConstraint(fields=('product_type', 'name'), name='unique_selling_case_name'),
        ),
    ]
