# Generated by Django 6.1.1 on 2026-10-01 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PER_VOLUME', 'Per Volume')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merchant_selling_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.merchantsellingcase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='pricing_amount_non_negative'), models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gte', 0), _connector='OR'), name='pricing_rate_non_negative')],
            },
        ),
    ]
