# Generated by Django 6.1.1 on 2026-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producttype',
            name='unique_product_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='sellingcase',
            name='unique_selling_case_name',
        ),
        migrations.AddField(
            model_name='sellingcase',
            name='volume_ml',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='sellingcase',
            constraint=models.UniqueConstraint(fields=('product_type', 'volume_ml'), name='unique_product_type_volume'),
        ),
        migrations.RemoveField(
            model_name='sellingcase',
            name='name',
        ),
    ]
