# Generated by Django 6.1.1 on 2026-09-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_producttype_unique_product_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingcase',
            name='volume_ml',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
