# Generated by Django 6.1.1 on 2026-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pricing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sellingcase',
            name='unique_selling_case',
        ),
        migrations.RemoveConstraint(
            model_name='sellingcase',
            name='selling_case_grade_positive',
        ),
        migrations.AddField(
            model_name='sellingcase',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sellingcase',
            constraint=models.UniqueConstraint(fields=('product_type', 'name'), name='unique_selling_case_per_product_type'),
        ),
        migrations.RemoveField(
            model_name='sellingcase',
            name='aging',
        ),
        migrations.RemoveField(
            model_name='sellingcase',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='sellingcase',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='sellingcase',
            name='sale_mode',
        ),
    ]
