# Generated by Django 6.1.1 on 2026-10-02 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_sellingcase_unique_selling_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('merchant_selling_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configurations', to='catalog.merchantsellingcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant_selling_case', 'grade'), name='unique_grade_per_merchant_selling_case')],
            },
        ),
    ]
