# Generated by Django 6.1.1 on 2026-10-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gradeconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='pricing_type',
            new_name='behavior',
        ),
    ]
