# Generated by Django 6.1.1 on 2026-09-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configurations', to='catalog.merchant')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configurations', to='catalog.producttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'product_type'), name='unique_merchant_product_type')],
            },
        ),
    ]
