# Generated by Django 6.1.1 on 2026-09-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merchantproductconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantproductconfiguration',
            name='default_price',
        ),
        migrations.AddField(
            model_name='sellingcase',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
