# Generated by Django 6.1.1 on 2026-10-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_pricing_type_pricing_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='grade_configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='merchant_selling_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.merchantsellingcase'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grade_configuration__isnull', True), ('merchant_selling_case__isnull', False)), models.Q(('grade_configuration__isnull', False), ('merchant_selling_case__isnull', True)), _connector='OR'), name='pricing_exactly_one_owner'),
        ),
    ]
