# Generated by Django 6.1.1 on 2026-09-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_merchantproductconfiguration_default_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingcase',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
