# Generated by Django 6.1.1 on 2026-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pricing_grade_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricing',
            name='pricing_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='pricing',
            name='pricing_rate_non_negative',
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='pricing_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gt', 0), _connector='OR'), name='pricing_rate_non_negative'),
        ),
    ]
