# Generated by Django 6.1.1 on 2026-09-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_move_merchant_to_merchants'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingcase',
            name='default_price',
        ),
        migrations.AddField(
            model_name='merchantproductconfiguration',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='MerchantSellingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_case_configurations', to='merchants.merchant')),
                ('selling_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_configurations', to='catalog.sellingcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'selling_case'), name='unique_merchant_selling_case')],
            },
        ),
    ]
